In [4]:
import torch

frame = torch.randn(2, 3, 5, 4)
print(frame)

tensor([[[[-2.1652, -0.8340,  1.2277,  0.0472],
          [ 0.1628,  0.6298,  0.0804, -0.6588],
          [ 0.9122,  0.5863,  0.8479, -0.3764],
          [ 0.3112, -0.0835,  0.9994,  1.0744],
          [-0.4398, -0.6100,  1.1250, -1.2360]],

         [[-0.9027, -0.2392, -0.0176,  1.4294],
          [-0.8966,  1.5377, -0.4295,  0.6504],
          [ 1.0600,  0.9158,  0.2250, -1.2704],
          [ 0.8455, -0.6437,  0.4035, -1.8794],
          [-1.8696, -1.5794, -0.2275, -0.1974]],

         [[ 1.9728, -0.8401, -0.9827,  0.9861],
          [-0.1883,  1.3442, -0.6882, -0.0291],
          [ 1.0799, -1.4659, -2.0946, -0.2933],
          [ 1.0271, -1.1435, -3.1286,  0.0491],
          [ 0.9609,  0.1578,  1.5014, -1.1742]]],


        [[[-0.6787, -0.1337, -0.9849, -0.6768],
          [-0.9656,  1.8746,  0.6913,  0.2256],
          [ 1.1479,  1.1300,  1.6408,  1.1600],
          [ 1.2687,  0.7335, -0.6443, -0.1714],
          [ 0.3324,  2.3056,  0.2107, -1.6239]],

         [[-1.8975,  0.2974, -

In [5]:
t = 1
print(frame[:, t])

tensor([[[-0.9027, -0.2392, -0.0176,  1.4294],
         [-0.8966,  1.5377, -0.4295,  0.6504],
         [ 1.0600,  0.9158,  0.2250, -1.2704],
         [ 0.8455, -0.6437,  0.4035, -1.8794],
         [-1.8696, -1.5794, -0.2275, -0.1974]],

        [[-1.8975,  0.2974, -0.5170,  0.3940],
         [ 1.4634, -1.1113, -1.5808,  0.4883],
         [-0.0171, -0.8967, -1.1760, -1.3252],
         [-0.7661,  1.0029,  0.4013, -0.1230],
         [ 0.1990,  0.2557, -0.9095,  0.2543]]])


In [6]:
torch.device('cpu')

device(type='cpu')

In [7]:
torch.device('cpu', 0)

device(type='cpu', index=0)

In [8]:
torch.device('cpu', 1)

device(type='cpu', index=1)

In [9]:
torch.device('cpu', 2)

device(type='cpu', index=2)

In [10]:
torch.device('cpu', 100)

device(type='cpu', index=100)

In [11]:
torch.device('cpu')

device(type='cpu')

In [1]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

listb = lista[1::2]
print(listb)

[2, 4, 6, 8, 10]


In [1]:
import torch
numbers = torch.arange(1, 10)
print(numbers)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [2]:
print(torch.__version__)

1.12.1


In [3]:
import torch
import numpy as np
print(torch.__version__)

1.12.1


In [13]:
a= np.arange(72).reshape(3,4,2,3)
print(a)

num = a.shape[1]
print(num)

lista = a[:,:,0]
print(lista)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]


 [[[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]]

  [[42 43 44]
   [45 46 47]]]


 [[[48 49 50]
   [51 52 53]]

  [[54 55 56]
   [57 58 59]]

  [[60 61 62]
   [63 64 65]]

  [[66 67 68]
   [69 70 71]]]]
4
[[[ 0  1  2]
  [ 6  7  8]
  [12 13 14]
  [18 19 20]]

 [[24 25 26]
  [30 31 32]
  [36 37 38]
  [42 43 44]]

 [[48 49 50]
  [54 55 56]
  [60 61 62]
  [66 67 68]]]


In [14]:
a[:,:,0] += num
print(a)

[[[[ 4  5  6]
   [ 3  4  5]]

  [[10 11 12]
   [ 9 10 11]]

  [[16 17 18]
   [15 16 17]]

  [[22 23 24]
   [21 22 23]]]


 [[[28 29 30]
   [27 28 29]]

  [[34 35 36]
   [33 34 35]]

  [[40 41 42]
   [39 40 41]]

  [[46 47 48]
   [45 46 47]]]


 [[[52 53 54]
   [51 52 53]]

  [[58 59 60]
   [57 58 59]]

  [[64 65 66]
   [63 64 65]]

  [[70 71 72]
   [69 70 71]]]]


In [15]:
t_1 = torch.randn(4, 5)
print(t_1)

tensor([[-1.0041,  0.1593, -0.8779,  1.1117, -0.2759],
        [-0.3267,  1.4914,  1.0904, -0.0229,  0.8103],
        [ 0.2355,  0.1386, -0.8539, -0.7806,  1.0804],
        [ 1.5184,  0.4209, -0.6098, -2.0629, -0.9200]])


In [16]:
print(t_1[1,2])

tensor(1.0904)


In [18]:
a = 3
b = 4
c = a * \
b
print(c)

12


In [23]:
mnist = np.load('mnist.npy')
print(mnist.shape)

(20, 10000, 64, 64)


In [24]:
path = 'data/moving-mnist-example/moving-mnist-train.npz'
train_mnist = path.split('/')
print(train_mnist)
mnist = np.load(path)
for key in mnist.keys():
    print("variable name:", key          , end="  ")
    print("type: "+ str(mnist[key].dtype) , end="  ")
    print("shape:"+ str(mnist[key].shape))

['data', 'moving-mnist-example', 'moving-mnist-train.npz']
variable name: clips  type: int32  shape:(2, 10000, 2)
variable name: dims  type: int32  shape:(1, 3)
variable name: input_raw_data  type: float32  shape:(200000, 1, 64, 64)


In [25]:
print(mnist['dims'])

[[ 1 64 64]]


In [33]:
a = torch.arange(189).reshape(21,3,3)
print(a.shape)
print(a)

torch.Size([21, 3, 3])
tensor([[[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[  9,  10,  11],
         [ 12,  13,  14],
         [ 15,  16,  17]],

        [[ 18,  19,  20],
         [ 21,  22,  23],
         [ 24,  25,  26]],

        [[ 27,  28,  29],
         [ 30,  31,  32],
         [ 33,  34,  35]],

        [[ 36,  37,  38],
         [ 39,  40,  41],
         [ 42,  43,  44]],

        [[ 45,  46,  47],
         [ 48,  49,  50],
         [ 51,  52,  53]],

        [[ 54,  55,  56],
         [ 57,  58,  59],
         [ 60,  61,  62]],

        [[ 63,  64,  65],
         [ 66,  67,  68],
         [ 69,  70,  71]],

        [[ 72,  73,  74],
         [ 75,  76,  77],
         [ 78,  79,  80]],

        [[ 81,  82,  83],
         [ 84,  85,  86],
         [ 87,  88,  89]],

        [[ 90,  91,  92],
         [ 93,  94,  95],
         [ 96,  97,  98]],

        [[ 99, 100, 101],
         [102, 103, 104],
         [105, 106, 107]],

        [[108, 10

In [38]:
a_1,a_2,a_3,a_4,a_5,a_6,a_7 = torch.split(a, 3, dim=0)
print(a_1.shape)
print(a_2.shape)

torch.Size([3, 3, 3])
torch.Size([3, 3, 3])


In [36]:
import torch.nn as nn
C, H, W = 5, 10, 10
input = torch.randn(C, H, W)
layer_norm = nn.LayerNorm([C,H,W])
output = layer_norm(input)
print(output.shape)

torch.Size([5, 10, 10])


In [39]:
for i in range(20):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [42]:
path = 'data/moving-mnist-example/moving-mnist-train.npz'
train_mnist = path.split('/')
print(train_mnist)
mnist = np.load(path)
for key in mnist.keys():
    print("variable name:", key          , end="  ")
    print("type: "+ str(mnist[key].dtype) , end="  ")
    print("shape:"+ str(mnist[key].shape))
print(mnist['clips'])

['data', 'moving-mnist-example', 'moving-mnist-train.npz']
variable name: clips  type: int32  shape:(2, 10000, 2)
variable name: dims  type: int32  shape:(1, 3)
variable name: input_raw_data  type: float32  shape:(200000, 1, 64, 64)
[[[     0     10]
  [    20     10]
  [    40     10]
  ...
  [199940     10]
  [199960     10]
  [199980     10]]

 [[    10     10]
  [    30     10]
  [    50     10]
  ...
  [199950     10]
  [199970     10]
  [199990     10]]]


In [5]:
import torch
import torch.nn as nn
import numpy as np
import random

indices = []

indices = np.arange(10, dtype='int32')
print(indices)

random.shuffle(indices)
print(indices)

[0 1 2 3 4 5 6 7 8 9]
[9 6 1 0 2 5 3 7 4 8]


In [6]:
import torch
import torch.nn as nn
import numpy as np

path = 'data/moving-mnist-example/moving-mnist-train.npz'
train_mnist = path.split('/')
print(train_mnist)
mnist = np.load(path)
for key in mnist.keys():
    print("variable name:", key          , end="  ")
    print("type: "+ str(mnist[key].dtype) , end="  ")
    print("shape:"+ str(mnist[key].shape))

['data', 'moving-mnist-example', 'moving-mnist-train.npz']
variable name: clips  type: int32  shape:(2, 10000, 2)
variable name: dims  type: int32  shape:(1, 3)
variable name: input_raw_data  type: float32  shape:(200000, 1, 64, 64)


In [9]:
print(mnist['dims'])
print(mnist['dims'][0])
print(mnist['dims'][1])

[[ 1 64 64]]
[ 1 64 64]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [14]:
list1 = [1, 2, 3, 4]
list2 = np.zeros((1, 1, 2, 3, 4))
print(list2)
list2[0] =list1
print(list2)

[[[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]
    [0. 0. 0. 0.]]]]]
[[[[[1. 2. 3. 4.]
    [1. 2. 3. 4.]
    [1. 2. 3. 4.]]

   [[1. 2. 3. 4.]
    [1. 2. 3. 4.]
    [1. 2. 3. 4.]]]]]


In [16]:
random_flip = np.random.random_sample(
        (20, 9))
print(random_flip)
print(random_flip<1)

[[0.16509464 0.25138721 0.69309787 0.46692707 0.29846119 0.97657439
  0.48625361 0.95191109 0.1069918 ]
 [0.26532712 0.57414459 0.25470442 0.88980886 0.81421634 0.58260303
  0.98930618 0.31259425 0.50975022]
 [0.94157957 0.71502737 0.15863429 0.9877541  0.62983408 0.86470082
  0.89923749 0.27963666 0.69795518]
 [0.12331123 0.97685886 0.40570745 0.42637758 0.14128342 0.98036037
  0.10951302 0.04430625 0.72450642]
 [0.21472108 0.18272332 0.55186307 0.89515621 0.39373907 0.8949497
  0.36325045 0.29686686 0.46609026]
 [0.16632059 0.8740224  0.39799511 0.32279556 0.46268695 0.23879206
  0.7940682  0.10134354 0.21478003]
 [0.10902859 0.90683452 0.75580515 0.34916304 0.97149857 0.13774255
  0.48219354 0.55478005 0.8652595 ]
 [0.43802965 0.51028082 0.37133714 0.69875261 0.65651167 0.2318166
  0.3670478  0.21068312 0.44166879]
 [0.80466905 0.94646378 0.12878027 0.66657319 0.67371257 0.77264044
  0.9244034  0.63572794 0.27596309]
 [0.66310607 0.8884232  0.83065827 0.38013649 0.88458347 0.0900904

In [18]:
ones = np.ones((1,2,3))
print(ones)
ones = np.array(ones)
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [19]:
a = torch.arange(10).reshape(5,2)
print(a)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [22]:
print(torch.split(a, 2, dim=1))
print(torch.split(a, 2, dim=0))

(tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),)
(tensor([[0, 1],
        [2, 3]]), tensor([[4, 5],
        [6, 7]]), tensor([[8, 9]]))


In [23]:
a = torch.arange(60).reshape(3,4,5)
print(a)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])


In [25]:
print(torch.split(a, 1, dim=1))
print(torch.split(a, 1, dim=0))
print(torch.split(a, 1, dim=2))

(tensor([[[ 0,  1,  2,  3,  4]],

        [[20, 21, 22, 23, 24]],

        [[40, 41, 42, 43, 44]]]), tensor([[[ 5,  6,  7,  8,  9]],

        [[25, 26, 27, 28, 29]],

        [[45, 46, 47, 48, 49]]]), tensor([[[10, 11, 12, 13, 14]],

        [[30, 31, 32, 33, 34]],

        [[50, 51, 52, 53, 54]]]), tensor([[[15, 16, 17, 18, 19]],

        [[35, 36, 37, 38, 39]],

        [[55, 56, 57, 58, 59]]]))
(tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]]), tensor([[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]), tensor([[[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]))
(tensor([[[ 0],
         [ 5],
         [10],
         [15]],

        [[20],
         [25],
         [30],
         [35]],

        [[40],
         [45],
         [50],
         [55]]]), tensor([[[ 1],
         [ 6],

In [26]:
lista = [1,2,3,4,5,6,7,8,9]
a = lista[-9:]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
listb = [-0.657, 0.765, 1.234]
listb = np.maximum(listb, 0)
print(listb)
listb = np.maximum(listb, 1)
print(listb)

[0.    0.765 1.234]
[1.    1.    1.234]


In [30]:
a = np.arange(60).reshape(3,4,5)
print(a)
num = np.size(a[0])
print(num)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
20


In [33]:
import cv2
img = np.random.random_sample((64, 64))
print(img)
img = np.uint8(img * 255)
print(img)
cv2.imwrite('demo.png', img)

[[0.42614244 0.08676841 0.36674904 ... 0.13572802 0.36004552 0.06555361]
 [0.87007797 0.18944848 0.42415457 ... 0.68288693 0.9138163  0.90028494]
 [0.81146699 0.08969745 0.04693466 ... 0.05995937 0.38454793 0.41760673]
 ...
 [0.46414608 0.08886762 0.83514351 ... 0.65658545 0.69625827 0.8619719 ]
 [0.46839632 0.69025562 0.97206394 ... 0.51168174 0.03027639 0.32702546]
 [0.2856299  0.55494743 0.87139907 ... 0.68040767 0.04306934 0.89963635]]
[[108  22  93 ...  34  91  16]
 [221  48 108 ... 174 233 229]
 [206  22  11 ...  15  98 106]
 ...
 [118  22 212 ... 167 177 219]
 [119 176 247 ... 130   7  83]
 [ 72 141 222 ... 173  10 229]]


True

In [35]:
import Metrics
img0 = torch.zeros(1,3,64,64)
img1 = torch.zeros(1,3,64,64)
lp_loss = Metrics.loss_fn_alex(img0, img1)
print(lp_loss.shape)

Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /Users/zhuzhirui/opt/anaconda3/envs/Pytorch_ESGAN/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
torch.Size([1, 1, 1, 1])
